name: git pull on PETER-PRAGUE

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  pull:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Pull repository from GitHub
        run: |
          cd C:\inetpub\wwwroot\basil.florist
          git config --global --add safe.directory C:/inetpub/wwwroot/basil.florist
          git pull